one = input("What is your favorite animal?")
two = input("Why do you like this animal?")
three = input("Where do they live?")
four = input("What is a fun fact about them?")
five = input("What color are they?")
print("Your favorite animal is" + one + " " + "because" + two + "." + "They live in" + three + " " + "and" + four + "." + "They are" + five +  ".")