one = input("What is your favorite animal?\n")
two = input("Why do you like this animal?\n")
three = input("Where do they live?\n")
four = input("What is a fun fact about them?\n")
five = input("What color are they?\n")
print("Your favorite animal is " + one + " " + "because " + two + "." + "They live in " + three + " " + "and " + four+ "." + "They are " + five +  ".")